name: Continuous integration
run-name: Integrate dependency ${{ github.event.client_payload.requires }}

on:
  repository_dispatch:
    types: [ integrate-dependency ]
  workflow_dispatch:

permissions:
  contents: write

jobs:

  integrate-dependency:
    name: Integrate dependency ${{ github.event.client_payload.requires }}
    runs-on: ubuntu-latest

    env:
      DEP_REQUIRES: "${{ github.event.client_payload.requires }}"
      CONAN_LOCKFILE: "proposed-conan.lock"

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Conan
        uses: conan-io/setup-conan@v1
        id: setup-conan
        with:
          config_urls: "https://github.com/msfrank/conan-config.git"

      - name: Configure Conan storage
        id: configure-conan-storage
        env:
          CONAN_HOME_BIN: ${{ steps.setup-conan.outputs.conan-home }}/bin
        run: |
          sudo python3 $CONAN_HOME_BIN/make_conan_storage --owner $USER --output-path /tmp/conan_storage_path
          echo "storage-path=$(cat /tmp/conan_storage_path)" >> "$GITHUB_OUTPUT"

      - name: Configure Conan global.conf
        env:
          CONAN_HOME_BIN: ${{ steps.setup-conan.outputs.conan-home }}/bin
          CONAN_CLIENT_CERT: ${{ secrets.CONAN_CLIENT_CERT }}
          CONAN_CLIENT_KEY: ${{ secrets.CONAN_CLIENT_KEY }}
          CONAN_CREDENTIALS_JSON: ${{ secrets.CONAN_CREDENTIALS_JSON }}
        run: |
          python3 $CONAN_HOME_BIN/generate_global_conf \
            --conan-home ${{ steps.setup-conan.outputs.conan-home }} \
            ${{ steps.configure-conan-storage.outputs.storage-path }}

      - name: Update dependency in ${{ env.CONAN_LOCKFILE }}
        id: update-lockfile
        env:
          CONAN_HOME_BIN: ${{ steps.setup-conan.outputs.conan-home }}/bin
        run: |
          conan lock update -vvv --requires="$DEP_REQUIRES" --lockfile=$CONAN_LOCKFILE --lockfile-out=$CONAN_LOCKFILE
          set +e
          git diff --quiet -- $CONAN_LOCKFILE
          echo "diff-status=$?" | tee -a "$GITHUB_OUTPUT"

      - name: Commit changes to ${{ env.CONAN_LOCKFILE }}
        if: ${{ steps.update-lockfile.outputs.diff-status == '1' }}
        env:
          GIT_TRACE: 1
        run: |
          # configure git
          git config --local user.name "CI Bot"
          git config --local user.email "ci-bot-noreply@exocortical.systems"
          #git config --unset "http.https://github.com/.extraheader"
          echo "updated git config"

          git remote set-url origin "https://${{secrets.PAT_CONTENTS_RW_EXOCORTIC}}@github.com/${{ github.repository }}.git"
          echo "set url for origin"

          # stage lock file
          git add $CONAN_LOCKFILE
          echo "staged $CONAN_LOCKFILE"

          # commit changes
          git commit -m "Update $CONAN_LOCKFILE: require $DEP_REQUIRES"
          echo "committed changes"

          # push revision using PAT for auth
          git push
          echo "pushed revision"
